services:

  db:
    container_name: database
    build: ./InvBank.Backend/InvBank.Backend.Infrastructure/Database/.
    volumes:
      - pg-data:/var/lib/postgresql/shared-data/
    ports:
      - "${EXP_PORT_PG}:5432"
    environment:
      - "POSTGRES_USER=${EXP_POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${EXP_POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${EXP_POSTGRES_DB}"
    networks:
      - app-network
  
  reiport_db_interface:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network

volumes:
  pg-data:
  backend:


networks:
  app-network:
    driver: bridge